[build]
  publish = "dist"
  command = "npm run build"

# Form notifications
[[plugins]]
  package = "@netlify/plugin-emails"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
